package com.IShnitko.Tr1Count_bot.util.user_state;

public enum UserState {
    DEFAULT,
    AWAITING_GROUP_ID,
    IN_THE_GROUP,
    AWAITING_GROUP_NAME,
    ADDING_EXPENSE_START,
    MEMBERS_MENU,
    AWAITING_EXPENSE_DETAILS,
    AWAITING_PAID_BY,
    AWAITING_SHARED_USERS,
    AWAITING_DATE,
    CONFIRMING_EXPENSE,
    ONLY_RETURN_TO_GROUP,
}
