package com.IShnitko.Tr1Count_bot.bot.model;

public enum UserState {
    DEFAULT,
    AWAITING_GROUP_ID,
    IN_THE_GROUP,
    AWAITING_GROUP_NAME,
    ADDING_EXPENSE_START,
    MEMBERS_MENU,
    AWAITING_EXPENSE_DETAILS,
    AWAITING_PAID_BY,
    AWAITING_SHARED_USERS,
    AWAITING_DATE,
    CONFIRMING_EXPENSE,
    ONLY_RETURN_TO_GROUP,
    ONLY_RETURN_TO_MEMBERS_MENU,
    ONLY_RETURN_TO_START,
    @Deprecated
    ONLY_RETURN_TO_EXPENSE_HISTORY,
    EXPENSE_HISTORY,
    EXPENSE_DELETE_CONFIRMATION,
    EDITING_EXPENSE
}
